In [1]:
import numpy as np
import copy


a = [[0, 0, 0, 0],
     [1, 5, 2, 0],
     [2, 6, 3, 1],
     [3, 7, 3, 2],
     [0, 8, 5, 4],
     [1, 9, 6, 4],
     [2, 10, 7, 5],
     [3, 11, 7, 6],
     [4, 12, 9, 8],
     [5, 13, 10, 8],
     [6, 14, 11, 9],
     [7, 15, 11, 10],
     [8, 12, 13, 12],
     [9, 13, 14, 12],
     [10, 14, 15, 13],
     [0, 0, 0, 0]]

x= np.array(a)
print((x.shape))

(16, 4)


In [2]:
v = np.zeros((16,))
gamma = 1
delta = 0.001
policy= np.ones((16,4))*0.25
reward= -1
k=0

def policy_evaluation(v):
    policy_p=np.zeros_like(policy,dtype=np.int32)
    for s in range(1,15):
        n=[0, 0, 0, 0]
        for a in range(4):
            s_p= x[s][a]
            n[a] = policy[s][a]*(reward+gamma*v[s_p])
    n= np.round(n, 1)
    for opti_a in np.flatnonzero(n==np.max(n)):
        policy_p[s][opti_a] = 1

    return policy_p

while True:
    
        v_temp = copy.copy(v)
        print("k=",k)
        print(v.reshape(4,4))
        print(policy_evaluation(v))
        for s in range(1,15):
            n=[0, 0, 0, 0]
            for a in range(4):
                s_p= x[s][a]
                n[a] = policy[s][a]*(reward+gamma*v_temp[s_p])
            
            v[s] = np.sum(n)
            # print(v)
      #   print((v-v_temp))
      #   break
        
        k+=1
        if (delta > np.abs(v- v_temp)).all():
            break

print(np.round(v,1).reshape(4,4))

k= 0
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 1 1]
 [0 0 0 0]]
k= 1
[[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]]
k= 2
[[ 0.   -1.75 -2.   -2.  ]
 [-1.75 -2.   -2.   -2.  ]
 [-2.   -2.   -2.   -1.75]
 [-2.   -2.   -1.75  0.  ]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]]
k= 3
[[ 0.     -2.4375 -2.9375 -3.    ]
 [-2.4375 -2.875  -3.     -2.9375]
 [-2.9375 -3.     -2.875  -2.4375]
 [-3.     -2.9375 -2.4375  0.    ]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 