In [1]:
import numpy as np
import copy

a = [[0, 5, 1, 0],
     [21, 21, 21, 21],
     [2, 7, 3, 1],
     [13, 13, 13, 13],
     [4, 9, 4, 3],
     [0, 10, 6, 5],
     [1, 11, 7, 5],
     [2, 12, 8, 6],
     [3, 13, 9, 7],
     [4, 14, 9, 8],
     [5, 15, 11, 10],
     [6, 16, 12, 10],
     [7, 17, 13, 11],
     [8, 18, 14, 12],
     [9, 19, 14, 13],
     [10, 20, 16,15],
     [11, 21, 17, 15],
     [12, 22, 18, 16],
     [13, 23, 19, 17],
     [14, 24, 19,18],
     [15, 20, 21, 20],
     [16, 21, 22, 20],
     [17, 22, 23, 21],
     [18, 23, 24, 22],
     [19, 24, 24, 23]]

x= np.array(a)
print((x.shape))










(25, 4)


In [6]:
def reward(s, s_p):
     if s==s_p:
        return -1
     elif s== 1 and s_p == 21 :
        return 10
     elif s== 3 and s_p == 13 :
        return 5 
     else:
        return 0 

# def update():

v = np.zeros((25,))
gamma = 0.9
delta = 0.001
while True:
    
        v_temp = copy.copy(v)
        for s in range(25):
            n=[0, 0, 0, 0]
            for a in range(4):
                s_p= x[s][a]
                r= reward(s,s_p)
                n[a] = 0.25*(r+gamma*v_temp[s_p])
            
            v[s] = np.sum(n)
            # print(v)
      #   print((v-v_temp))
      #   break
        if (delta > np.abs(v- v_temp)).all():
            break

print(np.round(v,1).reshape(5,5))

[[ 3.3  8.8  4.4  5.3  1.5]
 [ 1.5  3.   2.3  1.9  0.6]
 [ 0.1  0.7  0.7  0.4 -0.4]
 [-1.  -0.4 -0.3 -0.6 -1.2]
 [-1.9 -1.3 -1.2 -1.4 -2. ]]


C:\Users\user\AppData\Local\Temp\ipykernel_14320\2508589075.py:20: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  policy = np.zeros((25,4),dtype=np.int)
